### ISSUE TITLE
Default if no match

### ISSUE THREAD

**Issue by echatav** [Gabriel439/Haskell-Total-Library#4]
Total idiomatically supports defaulting if there is no match using `const default` or `\_ -> default` instead of `_case` like so:

```
data Example a b c = C1 a | C2 b | C3 c deriving (Generic)

makePrisms ''Example

instance (Empty a, Empty b, Empty c) => Empty (Example a b c)

getString :: Example String Double Int -> String
getString = const "not a string"
    & on _C1 (\s -> s)
```

Maybe this should be documented? Maybe a synonym `_default = const`?

**Comment by Gabriella439** [comment]
Wow, that never occurred to me!  Neat trick!

Yeah, I'd be happy to include `_default = const`.  Would you be able to write up a pull request for this?

**Comment by echatav** [comment]
Done and done. You can also emulate case statements that aren't lambda cases but I don't see much value in it. Also, I'm wondering about the type sig of `on`.

```
on
    :: ((a -> Either a Void) -> i -> Either l r)
    -> (l -> o)
    -> (r -> o)
    -> i
    -> o
```

Is it always the case in actual use that `a ~ l`?

**Comment by Gabriella439** [comment]
So if you use a lens then it will be the case that `a ~ l`.  I just left it with the more general type just to be safe since in theory the user might want to provide something more general than a lens.
