### ISSUE TITLE
Relax upper-bound on ghc-prim

### ISSUE THREAD

**Issue by k0ral** [Gabriel439/Haskell-Total-Library#7]
From what I've tested, the `total` library builds fine using `ghc-prim-0.4.0.0`, which is required by `base-4.8.0.0`, ie GHC 7.10 .
Would you please consider relaxing the current `< 0.4` bound on `ghc-prim` ?

Thank you.

**Comment by Gabriella439** [comment]
It might be possible to drop the explicit dependency on ghc-prim altogether.  If I remember correctly that was to support GHC versions older than 7.6, back when Debuan stable was still on 7.4, but now Debian is on 7.6, so I think we can get rid of it.
